config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

  resources :clients, shallow: true do
    get :favorite
    get :messages
    resources :surveys do
      resources :questions
    end
  end
  
  resources :customers

  namespace :api, defaults: {format: :json} do
      resources :sessions, only: [:create, :destroy]
      resources :customers do
        get :messages
        get :favorites
        get :rewards
        post :new_message
        post :favorite
        post :follow
        delete :remove_favorite
      end
      resources :clients do
        get :reviews
        get :survey
        get :favorited
        get :reward_profiles
        post :survey_response
        post :new_reward
      end
      resources :message_threads, only: [:show]
      
      resources :reviews do     #might deprecate this controllor maybe not.
        post :upvote
      end
  end

end

app/models/client.rb
class Client < ActiveRecord::Base

	#relations
	belongs_to :user
	belongs_to :category
	belongs_to :state
	has_many :reviews
	has_many :message_threads
	has_many :surveys
	has_many :favorites
	has_many :reward_profiles

	accepts_nested_attributes_for :user

	#validations
	validates :name, :address, :phone, :description, presence: true

	#set the rating for a client
	def set_rating
		self.update_attribute(:rating, get_rating)
	end

	#helper method to calculate rating based on reviews
	def get_rating
		num = self.reviews.count
		if num > 0
			total = 0
			self.reviews.each do |review|
				total += review.rating
			end
			return (total / num)
		else
			return nil
		end	
	end

	#Marks current survey as primary and turns all other off
	def mark_primary(survey)
		survey.update_attribute(flag: true)
		self.surveys.each do |s|
			if s.flag && s != survey
				s.update_attribute(flag: false)
			end
		end
	end

	#returns the survey that's marked as primary
	def get_primary
		self.surveys.each do |s|
			if s.flag
				return s
			end
		end
	end

	#return the max number of questions that a client is allowed to have for a survey
	def max_questions
		#Add to DB probably- maybe have different levels of membership?
		#Default to return 2
		return 2
	end

end

app/controllers/api/clients_controller.rb
module Api
	class ClientsController < Api::BaseController

		#GET: api/clients/client_id/reviews
		def reviews
			client = Clint.find(params[:client_id])
			@reviews = client.reviews
		end

		#GET api/clients/client_id/survey
		def survey
			client = Client.find(params[:client_id])
			@survey = client.get_primary
		end

		#GET api/clients/client_id/favorited
		def favorited 
			client = Client.find(params[:client_id])
			@favorites = client.favorites
		end

		#GET: api/clients/client_id/reward_profiles
		def reward_profiles
			client = Client.find(params[:client_id])
			@rewards = client.reward_profiles
		end

		#POST: api/clients/client_id/survey_response
		def survey_response 
			client = Client.find(params[:client_id])
			#TODO: Create survey response instance from params
			#Use model functions to keep controller skinny
			#Survey -> suvery_responses
			#Question -> question_responses
		end

		#POST: api/clients/client_id/new_reward
		def new_reward
			client = Client.find(params[:client_id])
			if client.reward_profiles.create(rewards_params)
				render json: client.reward_profiles, status: 201
			else
				render json: {errors: "invalid parameters"}, status: 403
			end
		end

		private

		def client_params
			params.require(:client).permit(:name, :address, :address_2, :city, :state, :zip_code, :phone, :menu, :rating, :description,
										   user_attributes: [:id, 
														  :email,
														  :password,
														  :password_confirmation
														]	
														)
		end

		def rewards_params
			params.require(:reward).permit(:name, :tier, :points, :max_redeem, :redeem_message)
		end

		def query_params
			params.permit(:name, :address, :phone, :menu, :rating, :description)
		end

	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	before_action :load_client, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:messages, :favorites]
	before_action :authenticate_with_token!, only: [:update, :destroy]

	def new
		@client = Client.new
	end

	def create
		@client = Client.create(client_params)
		if @client.save 
			redirect_to root_path, notice: 'Successfully created profile'
		else
			render 'new'
		end
	end

	def index
		@client = Clinet.all
	end

	def show
	end

	def edit
	end

	def update
		@client = current_user.client
		
		if @client.save
			redirect_to action: :show, id: @client.id 
		else
			render 'edit'
		end
	end

	def destroy
		@client.destroy
		redirect_to root_path, notice: "Company profile deleted"
	end

	#only show when user is logged in
	def favorite
		client = Client.find(params[:client_id])
		favorite = Favorite.new(client_id: params[:client_id])
		current_user.customer.favorites ||= []
		current_user.customer.favorites << favorite
		redirect_to root_path, notice: "Company added to favorites"
	end

	#view all messages
	def messages
		@client = Client.find(params[:client_id])
		@threads = @client.message_threads
	end

	private

	def load_client
		@client = Client.find(params[:id])
	end

	def client_params
		params.require(:client).permit(:name, :address, :address_2, :city, :state_id, :zip_code, :phone, :category_id, :description,
										user_attributes: [:id,
														  :email,
														  :password,
														  :password_confirmation
														]					
										)
	end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/edit.html.erb
<h1>Edit Company Profile</h1>

<%= form_for @client do |f| %>
	<% if @client.errors.any? %>
		<h2><%= pluralize(@client.errors.count, "error")  %> prohibited this article from being saved:</h2>
    	<% @client.errors.full_messages.each do |msg| %>
      		<li><%= msg %></li>
    	<% end %>		
    <% end %>
<br/>

    <div>
    	<%= f.label :name %><br/>
    	<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :address %><br/>
    	<%= f.text_field :address %>
	</div>
	<div>
		<%= f.label :address_2 %><br/>
    	<%= f.text_field :address_2 %>
	</div>
	<div>
		<%= f.label :city %><br/>
    	<%= f.text_field :city %>
	</div>
	<div>
		<%= f.label :state %><br/>
    	<%= f.select :state, State.for_select %>
	</div>
	<div>
		<%= f.label :zip_code %><br/>
    	<%= f.text_field :zip_code %>
	</div>

	<div>
		<%= f.label :phone %><br/>
		<%= f.text_field :phone %>
	</div>

	<div>
		<%= f.label :category_id %>
		<%= f.select :category_id, Category.for_select, include_blank: true %>
	</div>

	<div>
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</div>
	
	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/clients/messages.html.erb
<% if current_user.client == @client %>
	<h1>Your Company Messages</h1>
	<% @threads.each do |thread| %>
		<h4>Conversation with <%= thread.customer.first_name %></h4>
		<% thread.messages.each do |msg| %>
			<%= msg.body %><br/>
		<% end %>
	<% end %>
<% else %>
	<h2>You are not authorized to view this page</h2>
<% end %>

app/views/clients/new.html.erb
<h1>New Company Profile</h1>

<%= form_for @client do |f| %>
	<% if @client.errors.any? %>
		<h2><%= pluralize(@client.errors.count, "error")  %> prohibited this article from being saved:</h2>
    	<% @client.errors.full_messages.each do |msg| %>
      		<li><%= msg %></li>
    	<% end %>		
    <% end %>
<br/>
  
  	<%= f.fields_for :user_attributes, @client.user do |t| %>
  		<div>	
  			<%= t.label :email %><br/>
  			<%= t.email_field :email %>
  		</div>
  		<div>
			<%= t.label :password %><br/>
			<%= t.password_field :password %>
		</div>

		<div>
			<%= t.label :password_confirmation %><br/>
			<%= t.password_field :password_confirmation %>
		</div>
  	<% end %>

    <div>
    	<%= f.label :name %><br/>
    	<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :address %><br/>
    	<%= f.text_field :address %>
	</div>
	<div>
		<%= f.label :address_2 %><br/>
    	<%= f.text_field :address_2 %>
	</div>
	<div>
		<%= f.label :city %><br/>
    	<%= f.text_field :city %>
	</div>
	<div>
		<%= f.label :state_id %><br/>
    	<%= f.select :state_id, State.for_select %>
	</div>
	<div>
		<%= f.label :zip_code %><br/>
    	<%= f.text_field :zip_code %>
	</div>

	<div>
		<%= f.label :phone %><br/>
		<%= f.text_field :phone %>
	</div>

	<div>
		<%= f.label :category_id %>
		<%= f.select :category_id, Category.for_select, include_blank: true %>
	</div>

	<div>
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</div>
	
	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/clients/show.html.erb
<h1><%= @client.name %>'s Profile</h1>

<% if current_user %> 
	<% if current_user.customer != nil %>
		<%= link_to "Add to favorite", client_favorite_path(@client.id) %>
	<% elsif current_user.client == @client %>
		<%= link_to "View Messages", client_messages_path(@client.id) %>
	<% end %>
<% end %>
<br/>
<%= link_to "Create new survey", new_client_survey_path(@client) %>
<br/>
<%# IDEALLY THIS WOULD BE SET WHEN NEW REVIEWS ARE MADE%>
Rating: <%= @client.rating %>
<h3>Customer Reviews</h3>
<table>
<th>Reviewer</th>
<th>Review Detail</th>
<th>Rating</th>
<% @client.reviews.each do |review| %>
	<tr>
	<td><%= review.customer.first_name %></td>
	<td><%= review.detail %></td>
	<td><%= review.rating %></td>
	</tr>
<% end %>
</table>